window.PORTFOLIO_PROJECTS = Object.freeze({
  forma: {
    href: "./forma.html",
    title: "Forma",
    imageBase: "./assets/forma-cover-website",
    imageWidth: 2400,
    imageHeight: 1600,
    alt: "Forma furniture brand identity and digital experience",
    homeMeta: "Brand Identity<br>Website &amp; Packaging",
    listingMeta: "Brand Identity • Website • Packaging System",
    moreMeta: "Brand Identity • Website",
    related: ["nowAssist", "aiControlTower", "sheepguard"]
  },
  nowAssist: {
    href: "./now-assist-redesign.html",
    title: "Now Assist Redesign",
    shortTitle: "Now Assist",
    imageBase: "./assets/now-assist-cover-from-repdf",
    imageWidth: 2400,
    imageHeight: 1350,
    alt: "ServiceNow Now Assist redesign",
    imageClass: "project-image--nowassist-cover",
    homeMeta: "ServiceNow Internship<br>AI Product Design",
    listingMeta: "ServiceNow Internship • AI Product Design",
    moreMeta: "AI Research • Interaction Design",
    related: ["columnPinning", "aiControlTower", "sheepguard"]
  },
  aiControlTower: {
    href: "./ai-control-tower.html",
    title: "AI Pattern and Visual Language Unification",
    imageBase: "./assets/ai-pattern-cover-from-1pdf",
    imageWidth: 2400,
    imageHeight: 1350,
    alt: "ServiceNow AI Pattern and Visual Language Unification",
    imageClass: "project-image--aict-cover",
    homeMeta: "ServiceNow Internship<br>Enterprise AI",
    listingMeta: "ServiceNow Internship • Enterprise AI",
    moreMeta: "Product Design • Enterprise AI",
    related: ["dwHeader", "nowAssist", "columnPinning"]
  },
  dwHeader: {
    href: "./dw-simplified-header.html",
    title: "DW Simplified Header",
    imageBase: "./assets/dw-cover-from-2pdf",
    imageWidth: 2400,
    imageHeight: 1350,
    alt: "ServiceNow Dynamic Window simplified header",
    imageClass: "project-image--wide project-image--dw-cover",
    figureClass: "project-detail-more-card-image--dw-cover",
    homeMeta: "ServiceNow Internship<br>Workflow UX",
    listingMeta: "ServiceNow Internship • Workflow UX",
    moreMeta: "ServiceNow • Enterprise UX",
    related: ["aiControlTower", "nowAssist", "columnPinning"]
  },
  columnPinning: {
    href: "./column-pinning-exploration.html",
    title: "Column Pinning Exploration",
    shortTitle: "Column Pinning",
    imageBase: "./assets/column-pinning-cover-from-ds-pdf",
    imageWidth: 2400,
    imageHeight: 1350,
    alt: "ServiceNow column pinning exploration",
    imageClass: "project-image--wide project-image--column-cover",
    homeMeta: "ServiceNow Internship<br>Enterprise UX",
    listingMeta: "ServiceNow Internship • Enterprise UX",
    moreMeta: "ServiceNow • Enterprise UX",
    related: ["nowAssist", "aiControlTower", "sheepguard"]
  },
  sheepguard: {
    href: "./sheepguard.html",
    title: "SheepGuard",
    imageBase: "./assets/sheepguard/sheepguard-cover-45",
    imageWidth: 2400,
    imageHeight: 1350,
    alt: "SheepGuard scam detection app cover",
    homeMeta: "UI / UX Design<br>Scam Detection App",
    listingMeta: "UI / UX Design • Scam Detection App",
    moreMeta: "UI / UX Design • Scam Detection",
    related: ["forma", "nowAssist", "aiControlTower"]
  },
  allerpal: {
    href: "./allerpal.html",
    title: "AllerPal",
    imageBase: "./assets/allerpal/app-showcase",
    imageWidth: 2400,
    imageHeight: 1307,
    alt: "AllerPal accessibility and food allergy communication concept",
    homeMeta: "UI / UX Design<br>Accessibility &amp; Product Strategy",
    listingMeta: "UI / UX Design • Accessibility &amp; Product Strategy",
    moreMeta: "UI / UX Design • Accessibility",
    related: ["nowAssist", "aiControlTower"]
  },
  museumOfTechnology: {
    href: "./museum-of-technology.html",
    title: "Museum of Technology",
    shortTitle: "Museum of Technology",
    imageBase: "./assets/images/museum-of-technology/museum-1",
    imageWidth: 2048,
    imageHeight: 1152,
    alt: "Museum of Technology brand and wayfinding project cover",
    homeMeta: "Brand Identity<br>Environmental Design",
    listingMeta: "Brand Identity • Environmental Design",
    moreMeta: "Brand Identity • Environmental Design",
    related: ["forma", "nowAssist", "aiControlTower"]
  }
});
